import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "animate.css";
import { ThemeProvider } from "@/components/theme-provider";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Muslims Corner",
  description: "Generated by create next app",
};

// Add this to your existing imports
import { CartProvider } from "@/context/CartContext";
import { Toaster } from "react-hot-toast";

// Inside your RootLayout component, wrap the children with CartProvider
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          {/* Your existing layout components */}
          {children}
          <Toaster position="top-right" />
        </CartProvider>
      </body>
    </html>
  );
}
